---
title: "Lab5"
author: "Justin Stott"
date: "March 4, 2020"
output: html_document
---


Tutorial
```{r eval=FALSE}
library(tidyverse)
library(readr)


  download.file(url="https://ndownloader.figshare.com/files/2292169", destfile = "portal_data_joined.csv")
  surveys <- read_csv("portal_data_joined.csv")
  
  str(surveys)
  # View(surveys)
  
  select(surveys, plot_id, species_id, weight)
  select(surveys, -record_id, -species_id)
  filter(surveys, year == 1995)
  
  #pipes
  surveys2 <- filter(surveys, weight < 5)
  surveys_sml <- select(surveys2, species_id, sex, weight)
  surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
  
  surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
  
  surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

  surveys_sml
  
  surveys %>%
  mutate(weight_kg = weight / 1000)
  
  surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
  
  surveys %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
  
  surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
  
  surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
  
  surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
  
  surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))
  
  surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)
  
  surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))

  
  surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)
  
  surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))

  #Counting

  surveys %>%
    count(sex) 
  
  surveys %>%
    group_by(sex) %>%
    summarise(count = n())
  
  surveys %>%
    count(sex, sort = TRUE) 
  
  surveys %>%
  count(sex, species) 
  
  surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```

Hope its okay I couldnt get the origional function to work so i fiddled around to get the same result
```{r}
 SNPs <- read_tsv("data/23andMe_complete.txt", skip = 14, col_types = cols(chromosome = col_factor()))
```

Execise 1
```{r}
SNPs %>% 
  select(position, genotype) 
```

Exercise 2 
```{r}
SNPs %>% 
  filter(chromosome == "MT", genotype %in% c('A','T'))

```

Exercise 3 
```{r}
SNPs %>% 
  group_by(chromosome) %>% 
  summarize(minimum = min(position), maximum = max(position), total = sum(position))
```

Exercise 4
```{r}
SNPs %>% 
  group_by(chromosome) %>% 
  summarize(minimum = min(position), maximum = max(position), total = sum(position)) %>% 
  mutate(density = total/(maximum-minimum))
```

Exercise 5
```{r}
SNPs %>% 
  group_by(chromosome) %>% 
  summarize(minimum = min(position), maximum = max(position), total = sum(position)) %>% 
  mutate(density = total/(maximum-minimum)) %>% 
  arrange(density)
```

Exercise 6
```{r}
newdata=SNPs %>% 
  group_by(chromosome) %>% 
  summarize(minimum = min(position), maximum = max(position), total = sum(position)) %>% 
  mutate(density = total/(maximum-minimum))

write_csv(newdata, path = "data/Lab5Data.csv")
```



