---
title: "Lab9"
author: "Justin Stott"
date: "March 25, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)

report_03_11_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country.Region = "Country/Region", Province.State = "Province/State")

str(report_03_11_2020)
```

```{r fig.height=10}
report_03_11_2020 %>% 
  filter (Country.Region == "US") %>% 
  ggplot(aes(x = Confirmed,  y = reorder(Province.State, Confirmed))) + 
    geom_point() +
    ggtitle("Confirmed cases for each US State") +
    ylab("Country/Region") +
    xlab("Confirmed Cases")
```

```{r}
report_03_11_2020 %>% 
  group_by(Country.Region) %>% 
  summarise(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths))
```


```{r}
report_03_11_2020 %>% 
  group_by(Country.Region) %>% 
  summarise(Deaths = sum(Deaths)) %>% 
  arrange(desc(Deaths)) %>% 
  slice(1:20) %>% 
  ggplot(aes(y = Deaths,  x = reorder(Country.Region, Deaths))) + 
    geom_bar(stat = 'identity') +
    ggtitle("The 20 countries with the most reported COV19-related deaths") +
    ylab("Country/Region") +
    xlab("Deaths")+
  coord_flip()
```
```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province.State = "Province/State", Country.Region = "Country/Region")

head(time_series_confirmed)
```

```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province.State, Country.Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") %>% 
               group_by(Country.Region,Date) %>% 
               summarise(Confirmed = sum(Confirmed))

# convert date to data format
time_series_confirmed_long$Date <- mdy(time_series_confirmed_long$Date)
# Thanks to Prof. Chris Sunderland for this code chunk

head(time_series_confirmed_long)
```

```{r}
time_series_confirmed_long %>% 
  filter (Country.Region == "US") %>% 
    ggplot(aes(x = Date,  y = Confirmed)) + 
    geom_point() +
    geom_line() +
    ggtitle("US Confirmed COVID-19 Cases")
```
```{r}
time_series_confirmed_long %>% 
  filter (Country.Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Confirmed)) + 
    geom_point() +
    geom_line() +
    ggtitle("Confirmed COVID-19 Cases") +
    facet_wrap(~Country.Region, ncol=2, scales="free_y")

```
```{r}
time_series_confirmed_long %>% 
  filter (Country.Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Confirmed, color = Country.Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Confirmed COVID-19 Cases")
```
```{r}
library(maps)
library(viridis)

world <- map_data("world")

mybreaks <- c(1, 20, 100, 1000, 50000)
```
```{r}
ggplot() +
  geom_polygon(data = world, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(data=time_series_confirmed, aes(x=Long, y=Lat, size=`2/25/20`, color=`2/25/20`),stroke=F, alpha=0.7) +
  scale_size_continuous(name="Cases", trans="log", range=c(1,7),breaks=mybreaks, labels = c("1-19", "20-99", "100-999", "1,000-49,999", "50,000+")) +
  # scale_alpha_continuous(name="Cases", trans="log", range=c(0.1, 0.9),breaks=mybreaks) +
  scale_color_viridis_c(option="inferno",name="Cases", trans="log",breaks=mybreaks, labels = c("1-19", "20-99", "100-999", "1,000-49,999", "50,000+")) +
  theme_void() + 
  guides( colour = guide_legend()) +
  labs(caption = "") +
  theme(
    legend.position = "bottom",
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#ffffff", color = NA), 
    panel.background = element_rect(fill = "#ffffff", color = NA), 
    legend.background = element_rect(fill = "#ffffff", color = NA)
  )
```
```{r}
time_series_confirmed_long2 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
    rename(Province.State = "Province/State", Country.Region = "Country/Region") %>%
    pivot_longer(-c(Province.State, Country.Region, Lat, Long),
    names_to = "Date", values_to = "cumulative_cases") %>%
    mutate(Date = mdy(Date) - days(1),
        Place = paste(Lat,Long,sep="_")) %>%
    group_by(Place,Date) %>%
        summarise(cumulative_cases = ifelse(sum(cumulative_cases)>0,
        sum(cumulative_cases),NA_real_),
        Lat = mean(Lat),
        Long = mean(Long)) %>%
    mutate(Pandemic_day = as.numeric(Date - min(Date)))

head(time_series_confirmed_long2)
```

```{r}
static <- ggplot(subset(time_series_confirmed_long2,Date %in% seq(min(Date),max(Date),7)),
            aes(x = Long, y = Lat, size = cumulative_cases/1000)) +
            borders("world", colour = NA, fill = "grey90") +
            theme_bw() +
            geom_point(shape = 21, color='purple', fill='purple', alpha = 0.5) +
            labs(title = 'COVID-19 spread',x = '', y = '',
                 size="Cases (x1000))") +
            theme(legend.position = "right") +
            coord_fixed(ratio=1)+
            facet_wrap(.~Date,nrow=3)
static
```


Exercises

Daily Report 1
```{r }
report_03_20_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-20-2020.csv")) %>%
  rename(Country.Region = "Country/Region", Province.State = "Province/State")

report_03_20_2020 <- select(report_03_20_2020, Province.State, Country.Region, Confirmed, Deaths, Recovered)

report_03_20_2020 <- gather(report_03_20_2020,"Condition", "Count" , -Province.State, -Country.Region )



report_03_20_2020 %>% 
  filter (Country.Region == "US") %>% 
  ggplot(aes(y = Count,  x = reorder(Province.State,Count), fill = Condition)) + 
    geom_bar(stat = "identity", position = "stack") +
    ggtitle("Cases, Deaths and Recovery for each US State") +
    xlab("State") +
    ylab("Count")+ 
  coord_flip()
```
Daily Report 2
```{r}
report_03_20_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-20-2020.csv")) %>%
  rename(Country.Region = "Country/Region", Province.State = "Province/State")

report_03_20_2020 <- select(report_03_20_2020, Province.State, Country.Region, Confirmed, Deaths, Recovered)

report_03_20_2020 <- gather(report_03_20_2020,"Condition", "Count" , -Province.State, -Country.Region )



report_03_20_2020 %>% 
  filter(Count > 1000) %>% 
  ggplot(aes(y = Count,  x = reorder(Country.Region,Count), fill = Condition)) + 
    geom_bar(stat = "identity", position = "stack") +
    ggtitle("Cases, Deaths and Recovery for Countries with more than 1000 cases") +
    xlab("Country") +
    ylab("Count")+ 
  coord_flip()
```
Time Series data import
```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

time_series_deaths <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")


time_series_deaths_long <- time_series_deaths %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Deaths")

time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)

time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key"))

# which(is.na(time_series_long_joined$Confirmed))
# which(is.na(time_series_long_joined$Deaths))

### download the file
time_series_recovered <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

### convert to long format
time_series_recovered_long <- time_series_recovered %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Recovered")

### Create the Key
time_series_recovered_long <- time_series_recovered_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Recovered)

### Merge with prior table (only this time will delete the Key column
### because we have no further use for it)
time_series_long_joined <- full_join(time_series_long_joined,
              time_series_recovered_long, by = c("Key")) %>% 
    select(-Key)
# head(time_series_long_joined)

time_series_long_joined$Date <- mdy(time_series_long_joined$Date)

time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```
Time Series 1
```{r}
most_cases = time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  top_n( n = 3, wt = Confirmed) %>% 
  select(Country_Region)


time_series_long_joined %>% 
    filter(Date >= "2020-03-01") %>% 
    group_by(Country_Region, Date) %>% 
    summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
    filter (Country_Region %in% most_cases$Country_Region) %>%
    ggplot(aes(x = Date,  y = Confirmed, fill = Country_Region)) + 
    geom_bar(stat = "identity", position = 'dodge') +
    ggtitle("Confirmed COVID-19 Cases, in top 3 reported countries")
```
Time Series 2
```{r}
most_cases = time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  top_n( n = 3, wt = Confirmed) %>% 
  select(Country_Region)


time_series_long_joined %>% 
    filter(Date >= "2020-03-01") %>% 
    group_by(Country_Region, Date) %>% 
    summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
    filter (Country_Region %in% most_cases$Country_Region) %>%
    ggplot(aes(x = Date,  y = Deaths, fill = Country_Region)) + 
    geom_bar(stat = "identity", position = 'dodge') +
    ggtitle("COVID-19 Deaths in top 3 reported countries ")
```
Map 1
```{r}
time_series_long_joined %>% 
  filter(Date == "2020-03-25") %>% 
  ggplot( aes(x = Long, y = Lat, size = Deaths/Confirmed))+
  borders("world", colour = NA, fill = "grey90")+
  geom_point( fill = "blue", color = "blue", alpha = .4)+
  theme_bw()+
  labs(title = "Ratio of Deaths To Confirmed Cases")


```
Map 2 
```{r}
time_series_long_joined %>% 
  filter(Date == "2020-03-25") %>% 
  ggplot( aes(x = Long, y = Lat, size = Deaths/Recovered))+
  borders("world", colour = NA, fill = "grey90")+
  geom_point( fill = "green", color = "green", alpha = .4)+
  theme_bw()+
  labs(title = "Ratio of Deaths To Recovered Cases")
```





